
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Visitor',
  description: 'Generated by Visitor',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-green-100">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
